using PyPlot

function _showimage(predict_phi, x, y, count, image_size, date, counts)
    if count==0
        if length(size(predict_phi))==2
            predict_phi = reshape(predict_phi,(image_size,image_size,1,1))
        end
        @info("Ploting Result"*counts)
        pred_show = Array(predict_phi)
        x_show = Array(x)
        y_show = Array(y)
        pred_show = reshape(pred_show,(size(predict_phi)[1],size(predict_phi)[2]))
        x_show = reshape(x_show,(size(x_show)[1],size(x_show)[2]))
        y_show = reshape(y_show,(size(y_show)[1],size(y_show)[2]))
        figure("pred_show")
        title("Prediction")
        imshow(pred_show)
        colorbar()
        savefig(date*"_predict"*counts*".png")
        close("pred_show")
        figure("x_show")
        title("Rho")
        imshow(x_show)
        colorbar()
        savefig(date*"_rho"*counts*".png")
        close("x_show")
        figure("y_show")
        title("Phi")
        imshow(y_show)
        colorbar()
        savefig(date*"_phi"*counts*".png")
        close("y_show")
        figure("difference")
        title("Error")
        imshow(pred_show-y_show)
        colorbar()
        savefig(date*"_error"*counts*".png")
        close("difference")
    end
end
